[package]
name = "sloggers"
version = "0.3.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "This library provides frequently used slog loggers and convenient functions"
homepage = "https://github.com/sile/sloggers"
repository = "https://github.com/sile/sloggers"
readme = "README.md"
keywords = ["logger"]
license = "MIT"

[badges]
travis-ci = {repository = "sile/sloggers"}
codecov = {repository = "sile/sloggers"}

[dependencies]
chrono="0.4"
libflate = "0.1"
serde = "1"
serde_derive = "1"
slog = "2"
slog-async = "2"
slog-term = "2"
slog-scope = "4"
slog-kvfilter = "~0.7"
slog-stdlog = "3"
trackable = "0.2.19"
regex="1"

[dev-dependencies]
clap = "2"
serdeconv = "0.3"
tempdir = "0.3"
